#!/usr/bin/env bash
# script used to display information about subdomains
# Ignore shellcheck case SC2086 (line still added just in case)
obtain_dns()
{
    data=$(dig $i.$1 | awk '/ANSWER SECTION:/ {getline; print $4}')
    terminus=$(dig $i.$1 | awk '/ANSWER SECTION:/ {getline; print $5}')
}

if [ -z $2 ]; then
    for i in "www" "lb-01" "web-01" "web-02"; do
	obtain_dns $1
	echo "The subdomain $i is a $data record and points to $terminus"
    done
else
    i=$2
    obtain_dns $1
    echo "The subdomain $i is a $data record and points to $terminus"
fi
