#!/usr/bin/env bash
#script that installs and configures HAproxy on lb-01 server.

# Step 1- Updates the package list
sudo apt-get update

# Step 2-  Installs HAproxy
sudo apt -y install haproxy

# Step 3-  Append the HAproxy configuration to the end of the configuration file
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_web
    bind *:80
    default_backend rgw
backend rgw
    balance roundrobin
    server  110194-web-01 52.87.221.0:80 check
    server  110194-web-02 18.209.152.146:80 check
EOT

# Step 4-  Restart HAproxy inorder to apply the new configuration
sudo service haproxy restart
