#!/usr/bin/env bash
# Configures server to make sure Nginx is running and listening on port 80
# of all the server's active IPv4 IPs

# Update package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Ensure Nginx is configured to listen on port 80
sed -i "s/listen  .*/listen 80;/" /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart
