#!/usr/bin/env bash
# make sure nginx is pointing at port 80
rm -rf /etc/nginx/sites-enabled/*
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/                                  
service nginx restart
