#!/usr/bin/env bash
# Configures server to make sure Nginx is running and listening on port 80
# of all the server's active IPv4 IPs

#updates the package lists for upgrades and new package installations
apt-get update

#installs Nginx using apt-get

#uses sed to add a line to listen on all active IPv4 IPs on port 80 in the /etc/nginx/sites-available/default file.
apt-get install -y nginx
sed -i "s/listen 80 default_server;/listen 80 default_server;\\nlisten [::]:80 default_server;/" /etc/nginx/sites-available/default
service nginx start

