#!/usr/bin/env bash
# a scipt that fixes a given container so that Nginx is running as the nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf

# Start the nginx service as the nginx user
sudo -u nginx service nginx start
